"""
Django settings for NetworkBootManagementSystem project.

Generated by 'django-admin startproject' using Django 1.10.6.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""
# -*- coding:utf-8 -*-
import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'pqm-=15f)fko&mb!7p*l1$7!uxb^jmj&tbj5wpu)@z=y(@_h=@'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
# DEBUG = False

ALLOWED_HOSTS = [
    '172.16.66.66',
    '127.0.0.1',
    '192.168.96.96',
    '192.168.96.28',
    '192.168.66.99',
    'www.pxectrlsys.com',
    '192.168.96.20',
    '172.16.66.88'
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'networkbootsystem',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',  # 在Django中要使用post方式提交表单，需要在settings.py配置文件中将下面一行的内容给注释掉
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'NetworkBootManagementSystem.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'NetworkBootManagementSystem.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

# LANGUAGE_CODE = 'en-us'
LANGUAGE_CODE = 'zh-hans'

# TIME_ZONE = 'UTC'
TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

# 上传的文件能直接通过url打开，以及主url中设置
MEDIA_URL = '/networkbootsystem/'
# 设置文件相对路径，联合models设置：upload_to='isofiles'，将上传到http://127.0.0.1:8899/networkbootsystem/isofiles/1.JPG
# MEDIA_URL管理用户上传的多媒体文件的基础URL。

MEDIA_ROOT = os.path.join(BASE_DIR, 'networkbootsystem')
# 设置文件位置在/networkbootsystem/isofiles下，否则会直接保存到BASE_DIR根目录下，自动创建，路径为：http://127.0.0.1:8899/networkbootsystem/isofiles/1.JPG
# MEDIA_ROOT这些文件的本地路径，我们在前面添加BASE_DIR变量，动态生成该路径。

# NEW_BASE_DIR = 'C:\\Users\\liurui\\Desktop\\'
NEW_BASE_DIR = 'http://172.16.66.1:8088/images/'
# MEDIA_ROOT = os.path.join(NEW_BASE_DIR, 'networkbootsystem/')
# 自定义绝对路径NEW_BASE_DIR，将创建'pxeserver文件夹作为MEDIA_ROOT根目录，然后，根据模型定义upload_to='isofiles'，上传到C:\Users\liurui\Desktop\networkbootsystem\isofiles路径下。

SESSION_ENGINE = 'django.contrib.sessions.backends.db'   # 引擎（默认）
SESSION_EXPIRE_AT_BROWSER_CLOSE = True  # 是否关闭浏览器使得Session过期（默认）