# -*- coding:utf-8 -*-

from django.conf.urls import url
from . import views_clonezilla

urlpatterns = [
    url(r'^select_default_image_control.html$', views_clonezilla.select_default_image_control,
        name='select_default_image_control'),
    url(r'^select_default_image_control_choose$', views_clonezilla.select_default_image_control_choose,
        name='select_default_image_control_choose'),

    url(r'^select_default_image_control_add.html$', views_clonezilla.select_default_image_control_add,
        name='select_default_image_control_add'),
    url(r'^select_default_image_control_add$', views_clonezilla.select_default_image_control_add_bootstrap,
        name='select_default_image_control_add_bootstrap'),
    url(r'^select_default_image_control_delete$', views_clonezilla.select_default_image_control_delete,
        name='select_default_image_control_delete'),
    url(r'^select_default_image_control_update$', views_clonezilla.select_default_image_control_update,
        name='select_default_image_control_update'),


    url(r'^image_file_query_operation.html$', views_clonezilla.image_file_query_operation,
        name='image_file_query_operation'),
    url(r'^image_file_add.html$', views_clonezilla.image_file_add,
        name='image_file_add'),
    url(r'^image_file_delete.html$', views_clonezilla.image_file_delete,
        name='image_file_delete'),
    url(r'^image_file_update.html$', views_clonezilla.image_file_update,
        name='image_file_update'),

    url(r'^select_default_samba.html$', views_clonezilla.select_default_samba,
        name='select_default_samba'),
    url(r'^select_default_samba_add.html$', views_clonezilla.select_default_samba_add,
        name='select_default_samba_add'),
    url(r'^select_default_samba_delete.html$', views_clonezilla.select_default_samba_delete,
        name='select_default_samba_delete'),
    url(r'^select_default_samba_update.html$', views_clonezilla.select_default_samba_update,
        name='select_default_samba_update'),
    url(r'boot_from_clonezilla_auto$', views_clonezilla.boot_from_clonezilla_auto,
        name='boot_from_clonezilla_auto'),
    url(r'^boot_from_clonezilla_auto_delete.html$', views_clonezilla.boot_from_clonezilla_auto_delete,
        name='boot_from_clonezilla_auto_delete'),
    url(r'^boot_from_clonezilla_auto_update$', views_clonezilla.boot_from_clonezilla_auto_update,
        name='boot_from_clonezilla_auto_update'),
    url(r'^select_default_http$', views_clonezilla.select_default_http,
        name='select_default_http'),
    url(r'^select_default_http_update$', views_clonezilla.select_default_http_update,
        name='select_default_http_update'),
    url(r'^select_default_http_add$', views_clonezilla.select_default_http_add,
        name='select_default_http_add'),
    url(r'^update_select_default_image_http$', views_clonezilla.update_select_default_image_http,
        name='update_select_default_image_http'),
    url(r'^image_name_remote_manage$', views_clonezilla.image_name_remote_manage,
        name='image_name_remote_manage'),
    url(r'^image_rename_logs$', views_clonezilla.image_rename_logs,
        name='image_rename_logs'),
    url(r'^samba_sync_state$', views_clonezilla.samba_sync_state,
        name='samba_sync_state'),
    url(r'^image_remote_del$', views_clonezilla.image_remote_del,
        name='image_remote_del'),
    url(r'^image_remote_restore$', views_clonezilla.image_remote_restore,
        name='image_remote_restore'),
    url(r'^show_image_info$', views_clonezilla.show_image_info,
        name='show_image_info'),

    # url(r'^manager/boot_from_clonezilla_info_query_operation.html',
    #     views_clonezilla.boot_from_clonezilla_info_query_operation, name='boot_from_clonezilla_info_query_operation'),
    # url(r'^manager/boot_from_clonezilla_info_detail.html',
    #     views_clonezilla.boot_from_clonezilla_info_detail, name='boot_from_clonezilla_info_detail'),
    # url(r'^manager/boot_from_clonezilla_info_delete.html',
    #     views_clonezilla.boot_from_clonezilla_info_delete, name='boot_from_clonezilla_info_delete'),
    # url(r'^manager/boot_from_clonezilla_info_update.html',
    #     views_clonezilla.boot_from_clonezilla_info_update, name='boot_from_clonezilla_info_update'),
    # url(r'^manager/boot_from_clonezilla_info_add.html',
    #     views_clonezilla.boot_from_clonezilla_info_add, name='boot_from_clonezilla_info_add'),
    # url(r'^manager/boot_from_clonezilla_info_file_import.html',
    #     views_clonezilla.boot_from_clonezilla_info_file_import, name='boot_from_clonezilla_info_file_import'),


]
