# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-08 14:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BootFromClonezilla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='启动名称')),
                ('mac', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='MAC地址')),
                ('image_path', models.CharField(default='/home/partimag', max_length=100, verbose_name='镜像加载路径')),
                ('disk_num', models.CharField(default='sda', max_length=100, verbose_name='恢复硬盘编号')),
                ('available', models.BooleanField(verbose_name='是否启用')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('explain', models.TextField(max_length=100, null=True, verbose_name='说明')),
            ],
            options={
                'verbose_name': '一个Clonezilla恢复配置',
                'verbose_name_plural': '所有Clonezilla恢复配置',
            },
        ),
        migrations.CreateModel(
            name='BootFromClonezillaLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac', models.CharField(db_index=True, max_length=20, verbose_name='MAC地址')),
                ('ip', models.CharField(db_index=True, max_length=20, verbose_name='IP地址')),
                ('serial', models.CharField(max_length=100, verbose_name='服务代码')),
                ('image', models.CharField(max_length=100, verbose_name='镜像名称')),
                ('disk', models.CharField(max_length=100, verbose_name='恢复硬盘编号')),
                ('http_path', models.CharField(max_length=100, verbose_name='获取Http服务器')),
                ('samba_path', models.CharField(max_length=100, verbose_name='获取Samba服务器')),
                ('get_tag', models.BooleanField(verbose_name='是否获取')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '获取日志-Clonrzilla',
                'verbose_name_plural': '所有获取日志-Clonrzilla',
            },
        ),
        migrations.CreateModel(
            name='DefaultImageSelect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('select_name', models.CharField(max_length=30, verbose_name='选择默认启动镜像')),
                ('available', models.BooleanField(verbose_name='是否启用')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('explain', models.TextField(max_length=100, null=True, verbose_name='说明')),
            ],
            options={
                'verbose_name': '默认选择',
                'verbose_name_plural': '默认选择列表',
            },
        ),
        migrations.CreateModel(
            name='HttpServerList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('http_name', models.CharField(max_length=50, verbose_name='Http服务器名称')),
                ('http_ip', models.CharField(max_length=50, verbose_name='Http服务器IP')),
                ('http_port', models.CharField(blank=True, max_length=10, verbose_name='Http服务器端口')),
                ('http_folder', models.CharField(blank=True, max_length=50, verbose_name='文件目录')),
                ('available', models.BooleanField(verbose_name='是否启用')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('explain', models.TextField(max_length=100, null=True, verbose_name='说明')),
            ],
            options={
                'verbose_name': 'Http服务器',
                'verbose_name_plural': 'Http服务器列表',
            },
        ),
        migrations.CreateModel(
            name='ImageFilesList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='镜像名称')),
                ('image_name', models.CharField(max_length=50, unique=True, verbose_name='镜像文件名称')),
                ('disk_type', models.CharField(max_length=50, verbose_name='镜像硬盘类型')),
                ('disk_size', models.CharField(max_length=50, verbose_name='镜像硬盘容量')),
                ('available_model', models.CharField(max_length=100, verbose_name='可用电脑型号')),
                ('available', models.BooleanField(verbose_name='是否启用')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('explain', models.TextField(max_length=100, null=True, verbose_name='说明')),
            ],
            options={
                'verbose_name': '镜像文件',
                'verbose_name_plural': '镜像文件列表',
            },
        ),
        migrations.CreateModel(
            name='RestoreDiskNum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disk_name', models.CharField(max_length=10, verbose_name='恢复硬盘名称')),
                ('disk_num', models.CharField(max_length=10, verbose_name='恢复硬盘编号')),
                ('available', models.BooleanField(verbose_name='是否启用')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('explain', models.TextField(max_length=100, null=True, verbose_name='说明')),
            ],
            options={
                'verbose_name': '恢复硬盘编号',
                'verbose_name_plural': '恢复硬盘编号列表',
            },
        ),
        migrations.CreateModel(
            name='SambaServerList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('samba_name', models.CharField(max_length=50, verbose_name='Samba服务器名称')),
                ('samba_ip', models.CharField(max_length=50, verbose_name='Samba服务器IP')),
                ('samba_folder', models.CharField(max_length=50, verbose_name='镜像目录')),
                ('samba_user', models.CharField(blank=True, max_length=10, verbose_name='服务器用户')),
                ('samba_password', models.CharField(blank=True, max_length=10, verbose_name='服务器密码')),
                ('available', models.BooleanField(verbose_name='是否启用')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('explain', models.TextField(max_length=100, null=True, verbose_name='说明')),
            ],
            options={
                'verbose_name': 'Samba服务器',
                'verbose_name_plural': 'Samba服务器列表',
            },
        ),
        migrations.AddField(
            model_name='defaultimageselect',
            name='http_server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='networkbootsystem.HttpServerList', verbose_name='Http服务器选择'),
        ),
        migrations.AddField(
            model_name='defaultimageselect',
            name='image_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='networkbootsystem.ImageFilesList', verbose_name='镜像文件选择'),
        ),
        migrations.AddField(
            model_name='defaultimageselect',
            name='restore_disk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='networkbootsystem.RestoreDiskNum', verbose_name='恢复硬盘编号'),
        ),
        migrations.AddField(
            model_name='defaultimageselect',
            name='samba_server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='networkbootsystem.SambaServerList', verbose_name='Samba服务器选择'),
        ),
        migrations.AddField(
            model_name='bootfromclonezilla',
            name='http_server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='networkbootsystem.HttpServerList', verbose_name='Clonezilla文件地址'),
        ),
        migrations.AddField(
            model_name='bootfromclonezilla',
            name='image_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='networkbootsystem.ImageFilesList', verbose_name='镜像名称'),
        ),
        migrations.AddField(
            model_name='bootfromclonezilla',
            name='samba_server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='networkbootsystem.SambaServerList', verbose_name='Samba镜像服务器'),
        ),
    ]
