# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-08 14:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('networkbootsystem', '0002_auto_20170608_2221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bootfromclonezilla',
            old_name='disk_num',
            new_name='restore_disk',
        ),
        migrations.RenameField(
            model_name='bootfromclonezillalog',
            old_name='disk',
            new_name='restore_disk',
        ),
    ]
