# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-08 14:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('networkbootsystem', '0003_auto_20170608_2225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bootfromclonezillalog',
            old_name='restore_disk',
            new_name='disk_num',
        ),
    ]
