# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-08 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networkbootsystem', '0005_auto_20170608_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sambaserverlist',
            name='explain',
            field=models.TextField(blank=True, default='imagman', max_length=100, verbose_name='说明'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sambaserverlist',
            name='samba_password',
            field=models.CharField(max_length=10, verbose_name='服务器密码'),
        ),
        migrations.AlterField(
            model_name='sambaserverlist',
            name='samba_user',
            field=models.CharField(max_length=10, verbose_name='服务器用户'),
        ),
    ]
