# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-08 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networkbootsystem', '0006_auto_20170608_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bootfromclonezilla',
            name='explain',
            field=models.TextField(blank=True, default='1', max_length=100, verbose_name='说明'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='defaultimageselect',
            name='explain',
            field=models.TextField(blank=True, default='1', max_length=100, verbose_name='说明'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='imagefileslist',
            name='explain',
            field=models.TextField(blank=True, default='1', max_length=100, verbose_name='说明'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='restoredisknum',
            name='explain',
            field=models.TextField(blank=True, default='1', max_length=100, verbose_name='说明'),
            preserve_default=False,
        ),
    ]
