# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 01:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networkbootsystem', '0007_auto_20170608_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='sambaserverlist',
            name='samba_netspeed',
            field=models.CharField(default='/netspeedout', max_length=20, verbose_name='网速获取地址'),
            preserve_default=False,
        ),
    ]
