# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 01:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networkbootsystem', '0008_sambaserverlist_samba_netspeed'),
    ]

    operations = [
        migrations.CreateModel(
            name='BootSelect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='选择名称')),
                ('boot_name', models.CharField(max_length=30, verbose_name='选择启动方式')),
                ('available', models.BooleanField(verbose_name='是否启用')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('explain', models.TextField(blank=True, max_length=100, verbose_name='说明')),
            ],
            options={
                'verbose_name': '启动方式',
                'verbose_name_plural': '所有启动方式',
            },
        ),
        migrations.AlterModelOptions(
            name='defaultimageselect',
            options={'verbose_name': '默认Clonezilla选择', 'verbose_name_plural': '默认Clonezilla选择列表'},
        ),
        migrations.AlterField(
            model_name='sambaserverlist',
            name='samba_netspeed',
            field=models.CharField(default='/netspeedout', max_length=20, verbose_name='网速获取地址'),
        ),
    ]
