# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 02:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networkbootsystem', '0009_auto_20170609_0915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sambaserverlist',
            name='samba_netspeed',
        ),
        migrations.AddField(
            model_name='sambaserverlist',
            name='netspeed_path',
            field=models.CharField(blank=True, default='/netspeedout', max_length=20, verbose_name='网速获取地址'),
        ),
        migrations.AddField(
            model_name='sambaserverlist',
            name='netspeed_port',
            field=models.CharField(blank=True, max_length=10, verbose_name='Http服务器端口'),
        ),
    ]
