# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 05:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networkbootsystem', '0010_auto_20170609_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultimageselect',
            name='image_path',
            field=models.CharField(default='/home/partimag', max_length=100, verbose_name='镜像加载路径'),
        ),
        migrations.AlterField(
            model_name='defaultimageselect',
            name='available',
            field=models.BooleanField(verbose_name='是否启用(必须只能选择一项)'),
        ),
        migrations.AlterField(
            model_name='sambaserverlist',
            name='available',
            field=models.BooleanField(verbose_name='是否启用(必须至少有一项)'),
        ),
    ]
