# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-10 04:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networkbootsystem', '0012_auto_20170609_1910'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bootfromclonezilla',
            options={'verbose_name': 'Clonezilla启动选择', 'verbose_name_plural': 'Clonezilla启动选择列表'},
        ),
        migrations.AlterModelOptions(
            name='bootfromclonezillalog',
            options={'verbose_name': 'Clonezilla获取日志', 'verbose_name_plural': 'Clonezilla获取日志列表'},
        ),
        migrations.AlterModelOptions(
            name='bootfromiso',
            options={'verbose_name': 'ISO启动选择', 'verbose_name_plural': '1.2、ISO启动选择列表'},
        ),
        migrations.AlterModelOptions(
            name='bootselect',
            options={'verbose_name': '启动方式', 'verbose_name_plural': '0.0、选择启动方式'},
        ),
        migrations.AlterModelOptions(
            name='defaultimageselect',
            options={'verbose_name': 'Clonezilla默认选择', 'verbose_name_plural': '1.1、Clonezilla默认选择列表'},
        ),
        migrations.AlterModelOptions(
            name='imagefileslist',
            options={'verbose_name': 'Clonezilla镜像文件', 'verbose_name_plural': 'Clonezilla镜像文件列表'},
        ),
        migrations.AlterModelOptions(
            name='restoredisknum',
            options={'verbose_name': 'Clonezilla硬盘恢复', 'verbose_name_plural': 'Clonezilla硬盘恢复列表'},
        ),
        migrations.AlterField(
            model_name='bootselect',
            name='boot_name',
            field=models.CharField(max_length=30, unique=True, verbose_name='选择启动方式'),
        ),
    ]
