# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-10 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networkbootsystem', '0013_auto_20170610_1217'),
    ]

    operations = [
        migrations.CreateModel(
            name='BootFromISOLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac', models.CharField(db_index=True, max_length=20, verbose_name='MAC地址')),
                ('ip', models.CharField(db_index=True, max_length=20, verbose_name='IP地址')),
                ('serial', models.CharField(max_length=100, verbose_name='服务代码')),
                ('http_path', models.CharField(max_length=100, verbose_name='获取Http服务器')),
                ('iso_name', models.CharField(max_length=100, verbose_name='获取ISO名称')),
                ('get_tag', models.BooleanField(verbose_name='是否获取')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'ISO获取日志',
                'verbose_name_plural': 'ISO获取日志列表',
            },
        ),
    ]
