# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-10 13:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('networkbootsystem', '0015_defaultimageselect_get_way'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defaultimageselect',
            name='get_way',
        ),
    ]
