# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-10 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networkbootsystem', '0016_remove_defaultimageselect_get_way'),
    ]

    operations = [
        migrations.AddField(
            model_name='bootfromclonezillalog',
            name='get_way',
            field=models.CharField(default='自动', max_length=30, verbose_name='获取方式'),
            preserve_default=False,
        ),
    ]
