# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-11 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networkbootsystem', '0017_bootfromclonezillalog_get_way'),
    ]

    operations = [
        migrations.AddField(
            model_name='sambaserverlist',
            name='default',
            field=models.BooleanField(default='False', verbose_name='是否默认(必须只能选择一项)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sambaserverlist',
            name='netspeed_path',
            field=models.CharField(blank=True, default='/netspeedout', max_length=20, verbose_name='测速网速获取地址'),
        ),
        migrations.AlterField(
            model_name='sambaserverlist',
            name='netspeed_port',
            field=models.CharField(blank=True, max_length=10, verbose_name='测速Http服务器端口'),
        ),
    ]
