# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-17 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networkbootsystem', '0019_auto_20170613_1408'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bootfromclonezilla',
            options={'verbose_name': 'Clonezilla自动启动选择', 'verbose_name_plural': 'Clonezilla自动启动列表'},
        ),
        migrations.AlterField(
            model_name='defaultimageselect',
            name='select_name',
            field=models.CharField(max_length=60, unique=True, verbose_name='选择默认启动镜像'),
        ),
    ]
