# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-20 08:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networkbootsystem', '0021_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auto_add',
            field=models.CharField(choices=[('0', '否'), ('1', '是')], default=0, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='auto_alter',
            field=models.CharField(choices=[('0', '否'), ('1', '是')], default=0, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='auto_del',
            field=models.CharField(choices=[('0', '否'), ('1', '是')], default=0, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='auto_search',
            field=models.CharField(choices=[('0', '否'), ('1', '是')], default=0, max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=50, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(db_index=True, max_length=50, unique=True, verbose_name='用户名'),
        ),
    ]
