# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-20 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networkbootsystem', '0022_auto_20170620_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=200, verbose_name='密码'),
        ),
    ]
