# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-20 08:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('networkbootsystem', '0023_auto_20170620_1624'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='auto_add',
            new_name='auth_add',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='auto_alter',
            new_name='auth_alter',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='auto_del',
            new_name='auth_del',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='auto_search',
            new_name='auth_search',
        ),
    ]
