# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-26 05:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networkbootsystem', '0026_auto_20170626_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systeminstallstatus',
            name='process_time',
            field=models.CharField(blank=True, max_length=20, verbose_name='安装时长'),
        ),
    ]
