# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-26 06:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networkbootsystem', '0027_auto_20170626_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systeminstallstatus',
            name='complete_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='完成时间'),
        ),
        migrations.AlterField(
            model_name='systeminstallstatus',
            name='process_time',
            field=models.CharField(blank=True, max_length=20, verbose_name='安装时长(分钟)'),
        ),
        migrations.AlterField(
            model_name='systeminstallstatus',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='开始时间'),
        ),
        migrations.AlterField(
            model_name='systeminstallstatus',
            name='status',
            field=models.CharField(choices=[('-1', '未获取'), ('0', '进行中'), ('1', '已完成')], max_length=10, verbose_name='进度状态'),
        ),
    ]
