# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-26 06:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('networkbootsystem', '0028_auto_20170626_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systeminstallstatus',
            name='complete_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 26, 6, 10, 52, 214213, tzinfo=utc), verbose_name='完成时间'),
        ),
        migrations.AlterField(
            model_name='systeminstallstatus',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 26, 6, 10, 52, 214213, tzinfo=utc), verbose_name='开始时间'),
        ),
    ]
