# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-29 02:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networkbootsystem', '0030_auto_20170626_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systeminstallstatus',
            name='status',
            field=models.CharField(choices=[('-1', '未获取'), ('0', '进行中'), ('1', '已完成'), ('error', '超时异常')], default='-1', max_length=10, verbose_name='进度状态'),
        ),
    ]
