# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-08 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networkbootsystem', '0031_auto_20170629_1041'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAuthApply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='用户名')),
                ('auth_search', models.CharField(choices=[('0', '否'), ('1', '是')], max_length=2, verbose_name='查找权限')),
                ('auth_add', models.CharField(choices=[('0', '否'), ('1', '是')], max_length=2, verbose_name='增加权限')),
                ('auth_del', models.CharField(choices=[('0', '否'), ('1', '是')], max_length=2, verbose_name='删除权限')),
                ('auth_update', models.CharField(choices=[('0', '否'), ('1', '是')], max_length=2, verbose_name='更新权限')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='申请时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='处理时间')),
                ('statue', models.CharField(max_length=20, verbose_name='处理状态')),
            ],
            options={
                'verbose_name': '用户权限申请',
                'verbose_name_plural': '用户权限申请列表',
            },
        ),
    ]
