# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-08 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networkbootsystem', '0032_userauthapply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userauthapply',
            name='username',
            field=models.CharField(max_length=50, verbose_name='用户名'),
        ),
    ]
