# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-10 03:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networkbootsystem', '0033_auto_20170708_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userauthapply',
            name='statue',
            field=models.CharField(choices=[('-1', '已拒绝'), ('0', '未处理'), ('1', '已通过')], max_length=20, verbose_name='处理状态'),
        ),
    ]
