# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-11 01:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networkbootsystem', '0034_auto_20170710_1102'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=50, verbose_name='版本')),
                ('summary', models.CharField(max_length=100, verbose_name='摘要')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('details', models.TextField(blank=True, max_length=200, verbose_name='详情')),
            ],
        ),
    ]
