# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-12 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networkbootsystem', '0035_updatelog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='updatelog',
            options={'verbose_name': '更新日志', 'verbose_name_plural': '更新日志列表'},
        ),
        migrations.AddField(
            model_name='httpserverlist',
            name='default',
            field=models.BooleanField(default=False, verbose_name='是否默认(必须只能选择一项)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='httpserverlist',
            name='available',
            field=models.BooleanField(verbose_name='是否启用(必须至少有一项)'),
        ),
    ]
