# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-12 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networkbootsystem', '0036_auto_20170712_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='httpserverlist',
            name='http_name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Http服务器名称'),
        ),
    ]
