# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-03 03:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networkbootsystem', '0038_auto_20170803_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='available',
            field=models.BooleanField(default=True, verbose_name='是否启用'),
            preserve_default=False,
        ),
    ]
