# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-03 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networkbootsystem', '0040_userverificationcode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userverificationcode',
            options={'verbose_name': '验证码', 'verbose_name_plural': '验证码数据库'},
        ),
        migrations.AddField(
            model_name='userverificationcode',
            name='retrynum',
            field=models.IntegerField(default=1, verbose_name='验证码尝试次数'),
        ),
    ]
