# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-03 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networkbootsystem', '0041_auto_20170803_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='userverificationcode',
            name='sendnum',
            field=models.IntegerField(default=0, verbose_name='邮件发送次数'),
        ),
        migrations.AlterField(
            model_name='userverificationcode',
            name='retrynum',
            field=models.IntegerField(default=0, verbose_name='验证码尝试次数'),
        ),
    ]
