# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-09 06:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networkbootsystem', '0042_auto_20170803_2206'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiskSmartInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='硬盘序列号')),
                ('caption', models.CharField(blank=True, max_length=50, verbose_name='硬盘名称')),
                ('size', models.CharField(blank=True, max_length=10, verbose_name='硬盘大小G')),
                ('capacity', models.CharField(blank=True, max_length=10, verbose_name='实际容量G')),
                ('pnpdeviceid', models.CharField(blank=True, max_length=100, verbose_name='硬盘设备ID')),
                ('instancename', models.CharField(blank=True, max_length=100, verbose_name='硬盘实例名称')),
                ('reallocated', models.CharField(blank=True, max_length=10, verbose_name='重定位扇区数05')),
                ('poweron', models.CharField(blank=True, max_length=10, verbose_name='通电时间（小时）09')),
                ('powercycle', models.CharField(blank=True, max_length=10, verbose_name='通电次数0C')),
                ('currentpending', models.CharField(blank=True, max_length=10, verbose_name='等待重映射扇区数C5')),
                ('totalwritten', models.CharField(max_length=20, verbose_name='LBA写入总数F1')),
                ('ip', models.CharField(max_length=20, verbose_name='IP地址')),
                ('mac', models.CharField(max_length=20, verbose_name='MAC地址')),
                ('diskinfo', models.BooleanField(default=False, verbose_name='磁盘信息获取状态')),
                ('smartinfo', models.BooleanField(default=False, verbose_name='SMART信息获取状态')),
                ('disktime', models.DateTimeField(auto_now_add=True, verbose_name='磁盘信息获取时间')),
                ('smarttime', models.DateTimeField(auto_now_add=True, verbose_name='SMART信息获取时间')),
            ],
            options={
                'verbose_name': '硬盘SMART信息',
                'verbose_name_plural': '硬盘SMART信息',
            },
        ),
        migrations.AlterField(
            model_name='userverificationcode',
            name='inbox',
            field=models.CharField(blank=True, max_length=50, verbose_name='收件箱'),
        ),
        migrations.AlterField(
            model_name='userverificationcode',
            name='outbox',
            field=models.CharField(blank=True, max_length=50, verbose_name='发件箱'),
        ),
        migrations.AlterField(
            model_name='userverificationcode',
            name='sendnum',
            field=models.IntegerField(default=1, verbose_name='邮件发送次数'),
        ),
        migrations.AlterField(
            model_name='userverificationcode',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='注册时间'),
        ),
    ]
