# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-09 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networkbootsystem', '0043_auto_20170809_1454'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disksmartinfo',
            old_name='sn',
            new_name='serial',
        ),
        migrations.AlterField(
            model_name='disksmartinfo',
            name='totalwritten',
            field=models.CharField(blank=True, max_length=20, verbose_name='LBA写入总数F1'),
        ),
    ]
