# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-11 01:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networkbootsystem', '0044_auto_20170809_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disksmartinfo',
            name='poweron',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=86400, verbose_name='通电时间（小时）09'),
        ),
    ]
