# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-11 01:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networkbootsystem', '0053_auto_20170811_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disksmartinfo',
            name='capacity',
            field=models.CharField(blank=True, max_length=10, verbose_name='实际容量G'),
        ),
        migrations.AlterField(
            model_name='disksmartinfo',
            name='currentpending',
            field=models.CharField(blank=True, max_length=10, verbose_name='等待重映射扇区数C5'),
        ),
        migrations.AlterField(
            model_name='disksmartinfo',
            name='powercycle',
            field=models.CharField(blank=True, max_length=10, verbose_name='通电次数0C'),
        ),
        migrations.AlterField(
            model_name='disksmartinfo',
            name='poweron',
            field=models.CharField(blank=True, max_length=10, verbose_name='通电时间（小时）09'),
        ),
        migrations.AlterField(
            model_name='disksmartinfo',
            name='reallocated',
            field=models.CharField(blank=True, max_length=10, verbose_name='重定位扇区数05'),
        ),
        migrations.AlterField(
            model_name='disksmartinfo',
            name='size',
            field=models.CharField(blank=True, max_length=10, verbose_name='硬盘大小G'),
        ),
        migrations.AlterField(
            model_name='disksmartinfo',
            name='totalwritten',
            field=models.CharField(blank=True, max_length=20, verbose_name='LBA写入总数F1'),
        ),
    ]
