# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-28 01:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networkbootsystem', '0054_auto_20170811_0937'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=10, verbose_name='姓名')),
                ('num', models.DecimalField(decimal_places=0, max_digits=5, verbose_name='序号')),
                ('nightnum', models.DecimalField(decimal_places=0, default=0, max_digits=5, verbose_name='晚班临时序号')),
                ('meetnum', models.DecimalField(decimal_places=0, default=0, max_digits=5, verbose_name='例会临时序号')),
                ('weekendnum', models.DecimalField(decimal_places=0, default=0, max_digits=5, verbose_name='周末临时序号')),
                ('available', models.BooleanField(verbose_name='是否排班')),
            ],
            options={
                'verbose_name': '员工',
                'verbose_name_plural': '所有员工',
            },
        ),
        migrations.CreateModel(
            name='LegalDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('legalworkday', models.BooleanField(verbose_name='是否法定工作日')),
                ('legalrestday', models.BooleanField(verbose_name='是否法定休息日')),
            ],
            options={
                'verbose_name': '法定工作休息日',
                'verbose_name_plural': '值法定工作休息日',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='日期')),
                ('week', models.CharField(blank=True, max_length=10, verbose_name='星期')),
                ('workday', models.BooleanField(default=False, verbose_name='是否工作日')),
                ('nightduty', models.BooleanField(default=False, verbose_name='是否晚上值班')),
                ('regularmeeting', models.BooleanField(default=False, verbose_name='是否例会')),
                ('weekendduty', models.BooleanField(default=False, verbose_name='是否周末值班')),
                ('staff', models.CharField(max_length=10, null=True, verbose_name='值班人员')),
                ('realstaff', models.CharField(max_length=10, null=True, verbose_name='实际值班人员')),
            ],
            options={
                'verbose_name': '值班表',
                'verbose_name_plural': '值班表',
            },
        ),
    ]
