# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-30 01:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('networkbootsystem', '0055_employee_legalday_schedule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': '员工', 'verbose_name_plural': '值班表-所有员工'},
        ),
        migrations.AlterModelOptions(
            name='legalday',
            options={'verbose_name': '法定工作休息日', 'verbose_name_plural': '值班表-法定工作休息日'},
        ),
        migrations.AlterModelOptions(
            name='schedule',
            options={'verbose_name': '值班表', 'verbose_name_plural': '值班表-排班'},
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='regularmeeting',
            new_name='meetduty',
        ),
    ]
