# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-29 05:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networkbootsystem', '0057_wakeonlan'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('1', '硬件'), ('2', '软件'), ('3', '系统'), ('4', '网络')], max_length=2, verbose_name='分类')),
                ('topic', models.CharField(max_length=50, verbose_name='考察类型')),
                ('text', models.TextField(blank=True, max_length=200, verbose_name='考题')),
            ],
            options={
                'verbose_name': 'IT笔试题',
                'verbose_name_plural': 'IT笔试题库',
            },
        ),
    ]
