# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-29 07:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networkbootsystem', '0058_questionbank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionbank',
            name='type',
            field=models.CharField(max_length=10, verbose_name='分类'),
        ),
    ]
