# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-29 08:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('networkbootsystem', '0059_auto_20170929_1508'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionbank',
            old_name='type',
            new_name='category',
        ),
    ]
