# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-30 01:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networkbootsystem', '0061_questionbank_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionbank',
            name='image',
            field=models.ImageField(blank=True, upload_to='images', verbose_name='图片'),
        ),
    ]
