# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-09 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networkbootsystem', '0063_auto_20171001_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionbank',
            name='answer',
            field=models.TextField(blank=True, max_length=200, verbose_name='答案'),
        ),
    ]
