# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-22 02:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('networkbootsystem', '0065_auto_20171022_1020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='boot_select_id',
            new_name='boot_select',
        ),
    ]
