# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-08 09:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networkbootsystem', '0066_auto_20171022_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bootfromclonezilla',
            name='explain',
            field=models.TextField(blank=True, max_length=1000, verbose_name='说明'),
        ),
    ]
